# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Photo Widget' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photo Widget

  pod 'S3SwiftUIAppRater'
  pod 'Tatsi'
  pod 'Google-Mobile-Ads-SDK'

end

target 'Photo Widget ExtensionExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Photo Widget ExtensionExtension

end
